# Generated by Django 5.0.6 on 2024-06-07 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('subdomains', models.TextField()),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
